import type { Credential, SecurityAlert, SecurityEvent } from '@cryptovault/crypto-core'

// Timestamps relative to "now" so relative-time labels stay accurate
const now = new Date()
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60 * 1000)
const hoursAgo   = (h: number) => new Date(now.getTime() - h * 3600 * 1000)
const daysAgo    = (d: number) => new Date(now.getTime() - d * 86400 * 1000)

export const MOCK_CREDENTIALS: Credential[] = [
  {
    id: 'cred-001',
    userId: 'user-001',
    site: 'GitHub',
    url: 'https://github.com',
    username: 'alex@example.com',
    password: 'Gh!tHub_D3v#Secure2024XY',
    entropy: 112.4,
    strength: 'very-strong',
    category: 'work',
    mfaEnabled: true,
    notes: '',
    createdAt: new Date('2022-05-10'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'cred-002',
    userId: 'user-001',
    site: 'Netflix',
    url: 'https://netflix.com',
    username: 'alex@example.com',
    password: 'netflix123',
    entropy: 39.8,
    strength: 'weak',
    category: 'personal',
    mfaEnabled: false,
    notes: '',
    createdAt: new Date('2021-03-22'),
    updatedAt: new Date('2023-08-20'),
  },
  {
    id: 'cred-003',
    userId: 'user-001',
    site: 'Figma',
    url: 'https://figma.com',
    username: 'alex@example.com',
    password: 'F!gma_Des!gn#Pro98Secure',
    entropy: 98.7,
    strength: 'strong',
    category: 'work',
    mfaEnabled: true,
    notes: '',
    createdAt: new Date('2022-01-15'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'cred-004',
    userId: 'user-001',
    site: 'Twitter / X',
    url: 'https://x.com',
    username: 'alex_dev',
    password: 'netflix123',   // reused with Netflix
    entropy: 39.8,
    strength: 'weak',
    category: 'social',
    mfaEnabled: false,
    notes: 'Reused password — same as Netflix',
    createdAt: new Date('2020-02-29'),
    updatedAt: new Date('2023-05-12'),
  },
  {
    id: 'cred-005',
    userId: 'user-001',
    site: 'Binance',
    url: 'https://binance.com',
    username: 'alex@example.com',
    password: 'B!n@nce_Cr7pt0#Secure2024',
    entropy: 105.2,
    strength: 'very-strong',
    category: 'finance',
    mfaEnabled: true,
    notes: '',
    createdAt: new Date('2021-06-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'cred-006',
    userId: 'user-001',
    site: 'Gmail',
    url: 'https://mail.google.com',
    username: 'alex.smith@gmail.com',
    password: 'Gm@ilS3cure62bits!',
    entropy: 62.1,
    strength: 'moderate',
    category: 'personal',
    mfaEnabled: false,
    notes: '',
    createdAt: new Date('2020-01-10'),
    updatedAt: new Date('2023-11-08'),
  },
  {
    id: 'cred-007',
    userId: 'user-001',
    site: 'Telegram',
    url: 'https://telegram.org',
    username: '+1-555-867-5309',
    password: 'T3l3gr@m_S3cure88Strong!',
    entropy: 88.3,
    strength: 'strong',
    category: 'social',
    mfaEnabled: true,
    notes: '',
    createdAt: new Date('2021-09-15'),
    updatedAt: new Date('2024-01-30'),
  },
  {
    id: 'cred-008',
    userId: 'user-001',
    site: 'AWS Console',
    url: 'https://aws.amazon.com',
    username: 'alex-admin',
    password: 'AWSc0ns0le#Secure119XY!2024',
    entropy: 119.5,
    strength: 'very-strong',
    category: 'work',
    mfaEnabled: true,
    notes: '',
    createdAt: new Date('2022-11-20'),
    updatedAt: new Date('2024-02-28'),
  },
]

// 8 active alerts — Critical:2, High:1 → badge "3", Medium:3, Low:2
export const MOCK_ALERTS: SecurityAlert[] = [
  {
    id: 'alert-001',
    userId: 'user-001',
    type: 'phishing',
    severity: 'critical',
    title: 'Phishing site detected: netfl1x-login.com — autofill blocked',
    message: 'A lookalike domain "netfl1x-login.com" was detected. Credential autofill was blocked. Score: 92/100.',
    credentialId: undefined,
    resolved: false,
    createdAt: minutesAgo(2),
  },
  {
    id: 'alert-002',
    userId: 'user-001',
    type: 'breach',
    severity: 'critical',
    title: 'Netflix credentials found in data breach database',
    message: 'Your Netflix password was found in a known data breach database. Update immediately.',
    credentialId: 'cred-002',
    resolved: false,
    createdAt: hoursAgo(1),
  },
  {
    id: 'alert-003',
    userId: 'user-001',
    type: 'weak',
    severity: 'high',
    title: '4 passwords flagged with entropy below 40 bits',
    message: 'Netflix, Twitter/X and other passwords are below the recommended entropy threshold. Update them now.',
    credentialId: 'cred-002',
    resolved: false,
    createdAt: hoursAgo(3),
  },
  {
    id: 'alert-004',
    userId: 'user-001',
    type: 'reuse',
    severity: 'medium',
    title: 'Password reuse detected',
    message: 'Password reuse detected — "netflix123" used in 2 accounts (Netflix, Twitter/X). A breach of one exposes the other.',
    credentialId: 'cred-002',
    resolved: false,
    createdAt: hoursAgo(3),
  },
  {
    id: 'alert-005',
    userId: 'user-001',
    type: 'mfa',
    severity: 'medium',
    title: '2FA not enabled on 3 accounts',
    message: 'Netflix, Twitter/X, and Gmail have no two-factor authentication enabled.',
    credentialId: undefined,
    resolved: false,
    createdAt: daysAgo(2),
  },
  {
    id: 'alert-006',
    userId: 'user-001',
    type: 'phishing',
    severity: 'medium',
    title: 'Suspicious redirect chain detected on payment portal',
    message: 'A suspicious redirect chain was detected on a payment portal. Autofill was blocked to protect your credentials.',
    credentialId: undefined,
    resolved: false,
    createdAt: daysAgo(2),
  },
  {
    id: 'alert-007',
    userId: 'user-001',
    type: 'expired',
    severity: 'low',
    title: 'Vault unlocked successfully from Chrome — MacOS',
    message: 'Your vault was accessed from Chrome on MacOS. If this was not you, lock your vault immediately.',
    credentialId: undefined,
    resolved: false,
    createdAt: daysAgo(1),
  },
  {
    id: 'alert-008',
    userId: 'user-001',
    type: 'expired',
    severity: 'low',
    title: 'Passwords older than 6 months',
    message: "Netflix, Twitter/X, and Gmail passwords haven't been updated in over 6 months.",
    credentialId: undefined,
    resolved: false,
    createdAt: daysAgo(3),
  },
]

export const MOCK_EVENTS: SecurityEvent[] = [
  { id: 'evt-001', userId: 'user-001', type: 'phishing_scan',    timestamp: minutesAgo(2), details: { url: 'netfl1x-login.com', decision: 'BLOCK', message: 'Phishing site detected: netfl1x-login.com — autofill blocked' } },
  { id: 'evt-002', userId: 'user-001', type: 'vault_unlock',      timestamp: hoursAgo(1),  details: { ip: '192.168.1.1', device: 'MacBook Pro — Chrome', message: 'Vault unlocked successfully from Chrome — MacOS' } },
  { id: 'evt-003', userId: 'user-001', type: 'credential_update', timestamp: hoursAgo(3),  details: { site: 'Netflix', field: 'password', message: 'Netflix credentials found in data breach database' } },
  { id: 'evt-004', userId: 'user-001', type: 'password_generate', timestamp: hoursAgo(3),  details: { length: 24, entropy: 112.4, message: '4 passwords flagged with entropy below 40 bits' } },
  { id: 'evt-005', userId: 'user-001', type: 'phishing_scan',    timestamp: hoursAgo(3),  details: { url: 'ch4se-bank-secure.com', decision: 'BLOCK', message: 'Password reuse detected: "netflix123" used in 2 accounts' } },
  { id: 'evt-006', userId: 'user-001', type: 'vault_unlock',      timestamp: daysAgo(1),   details: { ip: '10.0.0.5', device: 'iPhone 16 Pro', message: 'Vault unlocked successfully from Chrome — MacOS' } },
  { id: 'evt-007', userId: 'user-001', type: 'vault_lock',        timestamp: daysAgo(1),   details: { reason: 'auto-timeout', message: 'Vault auto-locked after 15 min inactivity' } },
  { id: 'evt-008', userId: 'user-001', type: 'credential_delete', timestamp: daysAgo(2),   details: { site: 'Old Banking App' } },
  { id: 'evt-009', userId: 'user-001', type: 'vault_export',      timestamp: daysAgo(3),   details: { format: 'encrypted-json' } },
  { id: 'evt-010', userId: 'user-001', type: 'alert_dismissed',   timestamp: daysAgo(4),   details: { alertId: 'alert-005' } },
]
